//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojCRM.Areas.Stats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechDepControllers
    {
        public int id { get; set; }
        public string Agent { get; set; }
        public Nullable<int> TechIncomingCall { get; set; }
        public Nullable<int> TechOutgoingCall { get; set; }
        public Nullable<System.TimeSpan> TechCallDuration { get; set; }
        public Nullable<int> TechCompaniesActivated { get; set; }
        public Nullable<int> TechEmailCustomers { get; set; }
        public Nullable<int> TechEmailIntegrators { get; set; }
        public System.DateTime InsertDate { get; set; }
    }
}
