// <auto-generated />
namespace MojCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Jun302018Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jun302018Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201806301124501_Jun302018Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
