// <auto-generated />
namespace MojCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Feb102019Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feb102019Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201902100853187_Feb102019Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
